### ISSUE TITLE
DLAS throwing a torch._six error.

### ISSUE THREAD

**Issue by demonauthor** [152334H/DL-Art-School#58]
I installed the UI using the .setup DLAS.bat script and things were going well...followed along with the video tutorial and created a dataset, but when I click Start Training, it gives me a traceback error:

Traceback (most recent call last):
  File "C:\Users\oldgu\DL-Art-School\codes\train.py", line 12, in <module>
    from data.data_sampler import DistIterSampler
  File "C:\Users\oldgu\DL-Art-School\codes\data\__init__.py", line 6, in <module>
    from utils.util import opt_get
  File "C:\Users\oldgu\DL-Art-School\codes\utils\util.py", line 25, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

A quick look around and it looks like that module is deprecated? Is this a pytorch 2.0 issue or a me issue? Do I need to downgrade pytorch? I'm afraid it would break the whole thing.
I'm running Windows 11 with Miniconda 3

**Comment by demonauthor** [comment]
I "fixed" this by changing the import line in the util.py file to:
from torch import inf
instead of from torch._six import inf

Not sure if that actually fixes the issue or if it breaks something else, but it gets beyond that error.
