### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ysalex3d** [152334H/DL-Art-School#70]
Getting this error when I start training:

Disabled distributed training.
Path already exists. Rename it to [C:\Users\Yuri\DL-Art-School\experiments\_archived_230428-154734]
Traceback (most recent call last):
  File "C:\Users\Yuri\DL-Art-School\codes\train.py", line 380, in <module>
    trainer.init(args.opt, opt, args.launcher)
  File "C:\Users\Yuri\DL-Art-School\codes\train.py", line 51, in init
    util.mkdir_and_rename(
  File "C:\Users\Yuri\DL-Art-School\codes\utils\util.py", line 112, in mkdir_and_rename
    os.rename(path, new_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Yuri\\DL-Art-School\\experiments\\' -> 'C:\\Users\\Yuri\\DL-Art-School\\experiments\\_archived_230428-154734'
Press any key to continue . . .

Tried rolling back out of BitsandBytes and a handful of other things, but nothing working.

**Comment by KoenigSimon** [comment]
I ran into the same error, I managed to resolve it by giving the project a name
