### ISSUE TITLE
I need help with google colab

### ISSUE THREAD

**Issue by R3dPhil** [152334H/DL-Art-School#83]
Errormessage:
/content/DL-Art-School/codes
Traceback (most recent call last):
  File "/content/DL-Art-School/codes/train.py", line 12, in <module>
    from data.data_sampler import DistIterSampler
  File "/content/DL-Art-School/codes/data/__init__.py", line 6, in <module>
    from utils.util import opt_get
  File "/content/DL-Art-School/codes/utils/util.py", line 25, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

**Comment by R3dPhil** [comment]
I got this error when running the training code btw

**Comment by bibidentuhanoi** [comment]
I fixed this problem by removing the torch._six import inf in /content/DL-Art-School/codes/utils/util.py

**Comment by 1AakashK** [comment]
I fixed this by updating **from torch._six import inf** to **from torch import inf**. In line 25 of  /content/DL-Art-School/codes/utils/util.py
